name: Build & Test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Build & Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        go-version: [ 1.17.x ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Print Go version
        run: go version

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build project
        run: go build ./...

      - name: Run tests
        run: |
          go version
          go test -race ./...

      - id: results
        run: |
          id=$(echo ${{ github.event.after }} | cut -c -8)
          echo "::set-output name=id::$id"

          if [[ "${{ job.status }}" == succes ]]; then
            echo "::set-output name=status:::moneybag: SUCCESS"
          else
            echo "::set-output name=status:::hankey: FAILURE"
          fi          

      - name: Post to Slack
        id: slack
        uses: slackapi/slack-github-action@v1.16.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          channel-id: 'CCFC9EWH2'
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ steps.results.outputs.status }}"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:* `${{ github.repository }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch:* [${{ github.event.ref }}](${{ github.event.pull_request.html_url || github.event.head_commit.url }})"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Revision:* `${{ steps.results.outputs.id }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Committer:* `${{ github.actor }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Go Version:* `${{ matrix.go-version }}`"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*OS:* `${{ matrix.os }}`"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
